for i in range(20):
    print("        reg",str(i),".range(31, 0) = s_result_PE",str(16*i),".read() + 1;",sep='')
    print("        reg",str(i),".range(63, 32) = s_result_PE",str(16*i+1),".read() + 1;",sep='')
    print("        reg",str(i),".range(95, 64) = s_result_PE",str(16*i+2),".read() + 1;",sep='')
    print("        reg",str(i),".range(127, 96) = s_result_PE",str(16*i+3),".read() + 1;",sep='')
    print("        reg",str(i),".range(159, 128) = s_result_PE",str(16*i+4),".read() + 1;",sep='')
    print("        reg",str(i),".range(191, 160) = s_result_PE",str(16*i+5),".read() + 1;",sep='')
    print("        reg",str(i),".range(223, 192) = s_result_PE",str(16*i+6),".read() + 1;",sep='')
    print("        reg",str(i),".range(255, 224) = s_result_PE",str(16*i+7),".read() + 1;",sep='')
    print("        reg",str(i),".range(287, 256) = s_result_PE",str(16*i+8),".read() + 1;",sep='')
    print("        reg",str(i),".range(319, 288) = s_result_PE",str(16*i+9),".read() + 1;",sep='')
    print("        reg",str(i),".range(351, 320) = s_result_PE",str(16*i+10),".read() + 1;",sep='')
    print("        reg",str(i),".range(383, 352) = s_result_PE",str(16*i+11),".read() + 1;",sep='')
    print("        reg",str(i),".range(415, 384) = s_result_PE",str(16*i+12),".read() + 1;",sep='')
    print("        reg",str(i),".range(447, 416) = s_result_PE",str(16*i+13),".read() + 1;",sep='')
    print("        reg",str(i),".range(479, 448) = s_result_PE",str(16*i+14),".read() + 1;",sep='')
    print("        reg",str(i),".range(511, 480) = s_result_PE",str(16*i+15),".read() + 1;",sep='')
    print("        s_result_all.write(reg",str(i),");",sep='')
    print(" ")
